### ISSUE TITLE
Fix the wercker autotest.

### ISSUE THREAD

**Issue by darron** [DataDog/kvexpress#72]
Migrate to new wercker container.

**Comment by darron** [comment]
Thanks for changing that @miketheman - it works now - but it doesn't look like I have the ability to import it into the Datadog organization:

<img width="329" alt="screen shot 2016-01-24 at 10 22 06 am" src="https://cloud.githubusercontent.com/assets/5176/12538065/6b3ef6c2-c284-11e5-97fa-3d139c96c49b.png">

**Comment by miketheman** [comment]
I think I had to add you to the org - should be there now.

**Comment by darron** [comment]
Very cool - thanks! It's moved now.

Now to fix it so it passes!
